filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${INPUT_PATH:/volume/*.log}

  fields:
    log_topics: '${LOG_TOPIC:elib-gateway}'
#  tags: '${TAGS:elib-gateway}'
  scan_frequency: 10s
  tail_files: false
  exclude_lines: ['^$']
    
  multiline:
    pattern: '^\['
    negate: true
    match: after

processors:
- drop_fields:    
    fields: ["ecs","input","agent","log.offset"]

output.redis:
  enabled: true
  hosts: '${REDIS_HOSTS:192.168.10.212:10021}'
  password: '${REDIS_PASSWORD:hdfissufoiusn2378}'
  key: '${REDIS_KEY:product_logsrv}'
  db: '${REDIS_DB:1}'
