filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${INPUT_PATH:/volume/*.log}

processors:
- add_cloud_metadata:

output.redis:
  enabled: true
  hosts: '${REDIS_HOSTS:192.168.10.212:10021}'
  password: '${REDIS_PASSWORD:2lb097mcQ23iESrB}'
  data_type: '${REDIS_DATATYPE:list}'
  key: '${REDIS_KEY:product_logsrv}'
  db: '${REDIS_DB:2}'
