filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${INPUT_PATH:/volume/*.log}
  fields:
    log_topics: '${LOG_TOPIC:elib-gateway}'
  tags: '${TAGS:elib-gateway}'
  scan_frequency: 10s
  tail_files: true
  exclude_lines: ['^$']
  
  json.keys_under_root: true
  json.overwrite_keys: true
    
  multiline:
    pattern: '^\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}'
    negate: true
    match: after

processors:
  - drop_fields:    
      fields: ["ecs","input","agent","log.offset"]

output.redis:
  enabled: true
  hosts: '${REDIS_HOSTS:192.168.10.212:10021}'
  password: '${REDIS_PASSWORD:2lb097mcQ23iESrB}'
  key: '${REDIS_KEY:product_logsrv}'
  db: '${REDIS_DB:1}'
