filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ${INPUT_PATH:/volume/*.log}

  fields:
    log_topics: '${LOG_TOPIC:elib-gateway}'
#  tags: '${TAGS:elib-gateway}'
  scan_frequency: 10s
  tail_files: false
  exclude_lines: ['^$']
    
  multiline:
    pattern: '^\['
    negate: true
    match: after
    timeout: 5s

processors:
- drop_fields:    
    fields: ["ecs","input","agent","log.offset"]

output.redis:
  enabled: true
  hosts: '${REDIS_HOSTS:10.21.25.100:6380}'
  password: '${REDIS_PASSWORD:c8887d293}'
  key: '${REDIS_KEY:product_logsrv}'
  db: '${REDIS_DB:2}'
  timeout: 60
logging.level: warning
